import = [ "~/.config/alacritty/themes/themes/catppuccin_frappe.toml" ]

[font]
size = 15.0
offset = { x = 0, y = -1 }
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[colors.cursor]
text = "0xffffff"      # color of the character under the cursor
cursor = "0xa87d32"    # color of the cursor itself

[window]
padding = { x = 0, y = 0 }
dynamic_padding = false

